### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by cberner** [chadaustin/wired-sculpt-pcb#1]
Hi, thanks for the great blog post! I'm interested in using your PCB design to convert my Sculpt keyboard to be wired. What are the licensing terms of these PCB files?

**Comment by chadaustin** [comment]
Hi Chris! The license is whatever you want. :) Feel free to use them as you wish. I'll try to add an explicit COPYRIGHT.

**Comment by cberner** [comment]
Awesome, thanks!
